import { existsSync, writeFileSync, unlinkSync, mkdirSync, appendFileSync, chmodSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { homedir, platform } from 'node:os'
import { execSync } from 'node:child_process'

const PLIST_NAME = 'com.tokend.sync'
const PLIST_PATH = join(homedir(), 'Library', 'LaunchAgents', `${PLIST_NAME}.plist`)
const CRON_MARKER = '# tokend-auto-sync'
const TOKEND_DIR = join(homedir(), '.tokend')
const LOG_PATH = join(TOKEND_DIR, 'sync.log')
const WRAPPER_PATH = join(TOKEND_DIR, 'run-sync.sh')
export const DAEMON_RUN_ENV = 'TOKEND_DAEMON_RUN'

function logDaemon(msg: string) {
  if (!existsSync(TOKEND_DIR)) mkdirSync(TOKEND_DIR, { recursive: true })
  appendFileSync(LOG_PATH, `[${new Date().toISOString()}] ${msg}\n`)
}

/**
 * Write a wrapper shell script to ~/.tokend/run-sync.sh
 *
 * Why a wrapper instead of pointing daemon directly to the binary?
 * - npx cache paths are volatile (change on version update, cache cleanup)
 * - Global install requires network + permissions, may fail
 * - A wrapper at a STABLE path (~/.tokend/) uses npx at runtime,
 *   which always resolves to the latest cached/installed version
 * - If one run fails (network, cache miss), next run retries — no permanent breakage
 */
export function buildWrapperScript(nodeBinDir: string, syncCmd: string): string {
  return `#!/bin/bash
# Auto-generated by tokend-cli — do not edit
# This script is run by the system daemon every 5 minutes
export HOME="${homedir()}"
export PATH="${nodeBinDir}:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin"
export npm_config_cache="${join(homedir(), '.npm')}"
export ${DAEMON_RUN_ENV}="1"

${syncCmd} 2>&1

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] sync failed (exit $EXIT_CODE)" >> "${LOG_PATH}"
fi
  `
}

function isStableDaemonBinaryPath(binPath: string): boolean {
  if (!binPath) return false
  if (binPath.includes('/.npm/_npx/')) return false
  if (binPath.includes('/node_modules/.bin/')) return false
  return true
}

export function resolveDaemonSyncCommand(globalBin: string): string {
  return isStableDaemonBinaryPath(globalBin)
    ? `"${globalBin}" --quiet`
    : 'npx --yes tokend-cli@latest --quiet'
}

function writeWrapper(): string {
  if (!existsSync(TOKEND_DIR)) mkdirSync(TOKEND_DIR, { recursive: true })

  // Resolve node/npx paths for the wrapper
  let nodeBinDir: string
  try {
    nodeBinDir = dirname(execSync('which node', { encoding: 'utf8' }).trim())
  } catch {
    nodeBinDir = dirname(process.execPath)
  }

  // Also check if tokend-cli is globally installed — prefer that over npx
  let globalBin = ''
  try {
    globalBin = execSync('which tokend-cli 2>/dev/null', { encoding: 'utf8' }).trim()
    if (!existsSync(globalBin)) globalBin = ''
  } catch { /* not installed */ }

  const syncCmd = resolveDaemonSyncCommand(globalBin)

  const script = buildWrapperScript(nodeBinDir, syncCmd)

  writeFileSync(WRAPPER_PATH, script)
  chmodSync(WRAPPER_PATH, 0o755)
  logDaemon(`Wrapper written: ${WRAPPER_PATH} (cmd: ${syncCmd})`)
  return WRAPPER_PATH
}

export function shouldAutoInstallDaemon(env: NodeJS.ProcessEnv = process.env): boolean {
  return env[DAEMON_RUN_ENV] !== '1'
}

// ─── macOS LaunchAgent ───

function buildPlist(wrapperPath: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_NAME}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${wrapperPath}</string>
  </array>
  <key>StartInterval</key>
  <integer>300</integer>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${LOG_PATH}</string>
  <key>StandardErrorPath</key>
  <string>${LOG_PATH}</string>
</dict>
</plist>
`
}

function installMacDaemon(silent: boolean) {
  const wrapperPath = writeWrapper()

  const laDir = dirname(PLIST_PATH)
  if (!existsSync(laDir)) mkdirSync(laDir, { recursive: true })

  writeFileSync(PLIST_PATH, buildPlist(wrapperPath))
  try {
    execSync(`launchctl unload ${PLIST_PATH} 2>/dev/null`, { stdio: 'ignore' })
  } catch { /* ignore */ }
  execSync(`launchctl load ${PLIST_PATH}`)

  logDaemon('macOS daemon installed')
  if (!silent) {
    console.log('  ✓ 自动同步已开启 (每 5 分钟)')
    console.log(`    脚本: ${wrapperPath}`)
  }
  return true
}

// ─── Linux crontab ───

function installLinuxDaemon(silent: boolean) {
  const wrapperPath = writeWrapper()

  const cronLine = `*/5 * * * * ${wrapperPath} >> ${LOG_PATH} 2>&1 ${CRON_MARKER}`

  let existing = ''
  try {
    existing = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' })
  } catch { /* no crontab yet */ }

  const filtered = existing.split('\n').filter(l => !l.includes(CRON_MARKER)).join('\n').trimEnd()
  const newCrontab = filtered ? `${filtered}\n${cronLine}\n` : `${cronLine}\n`

  execSync(`echo ${JSON.stringify(newCrontab)} | crontab -`)

  logDaemon('Linux cron installed')
  if (!silent) {
    console.log('  ✓ 自动同步已开启 (每 5 分钟, crontab)')
    console.log(`    脚本: ${wrapperPath}`)
  }
  return true
}

// ─── Public API ───

export function installDaemon(silent = false): boolean {
  const os = platform()
  try {
    if (os === 'darwin') {
      return installMacDaemon(silent)
    } else if (os === 'linux') {
      return installLinuxDaemon(silent)
    } else {
      if (!silent) console.log(`  ⚠ 暂不支持 ${os} 自动同步，请手动定期运行: npx tokend-cli`)
      return false
    }
  } catch (err: any) {
    logDaemon(`ERROR installing daemon: ${err.message}`)
    if (!silent) console.error(`  ✗ 安装自动同步失败: ${err.message}`)
    return false
  }
}

export function uninstallDaemon() {
  const os = platform()

  if (os === 'darwin') {
    if (!existsSync(PLIST_PATH)) {
      console.log('  Daemon not installed')
      return
    }
    try {
      execSync(`launchctl unload ${PLIST_PATH}`)
    } catch { /* ignore */ }
    unlinkSync(PLIST_PATH)
    if (existsSync(WRAPPER_PATH)) unlinkSync(WRAPPER_PATH)
    console.log('  ✓ macOS daemon removed')
  } else if (os === 'linux') {
    try {
      const existing = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' })
      const filtered = existing.split('\n').filter(l => !l.includes(CRON_MARKER)).join('\n').trimEnd()
      execSync(`echo ${JSON.stringify(filtered ? filtered + '\n' : '')} | crontab -`)
      if (existsSync(WRAPPER_PATH)) unlinkSync(WRAPPER_PATH)
      console.log('  ✓ Cron job removed')
    } catch {
      console.log('  No cron job found')
    }
  } else {
    console.log(`  ⚠ ${os}: no daemon to remove`)
  }
}

export function daemonStatus() {
  const os = platform()

  if (os === 'darwin') {
    if (!existsSync(PLIST_PATH)) {
      console.log('  Daemon: not installed')
      console.log('  Run: npx tokend-cli daemon install')
      return
    }
    try {
      const out = execSync(`launchctl list ${PLIST_NAME} 2>&1`, { encoding: 'utf8' })
      const exitLine = out.split('\n').find(l => l.includes('LastExitStatus'))
      const pidLine = out.split('\n').find(l => l.includes('PID'))
      const exitCode = exitLine?.match(/(\d+)/)?.[1]
      const isOk = exitCode === '0' || exitCode === undefined

      if (pidLine) {
        console.log('  Daemon: running ✓')
        console.log(`  ${pidLine.trim()}`)
      } else if (isOk) {
        console.log('  Daemon: idle (waiting for next 5-min interval)')
      } else {
        console.log(`  Daemon: FAILING (exit ${exitCode})`)
        console.log('  Fix: npx tokend-cli daemon install')
      }
    } catch {
      console.log('  Daemon: installed but not running')
      console.log('  Fix: npx tokend-cli daemon install')
    }
  } else if (os === 'linux') {
    try {
      const crontab = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' })
      if (crontab.includes(CRON_MARKER)) {
        console.log('  Daemon: active (cron, every 5 min) ✓')
      } else {
        console.log('  Daemon: not installed')
        console.log('  Run: npx tokend-cli daemon install')
      }
    } catch {
      console.log('  Daemon: not installed')
      console.log('  Run: npx tokend-cli daemon install')
    }
  } else {
    console.log(`  ⚠ ${os}: auto-sync not supported`)
  }

  // Show wrapper info
  if (existsSync(WRAPPER_PATH)) {
    console.log(`  脚本: ${WRAPPER_PATH}`)
  }

  // Show recent log
  if (existsSync(LOG_PATH)) {
    try {
      const log = execSync(`tail -5 ${LOG_PATH}`, { encoding: 'utf8' }).trim()
      if (log) {
        console.log('\n  Recent log:')
        log.split('\n').forEach(l => console.log(`    ${l}`))
      }
    } catch { /* ignore */ }
  }
}
