import { existsSync, writeFileSync, unlinkSync, mkdirSync, appendFileSync, chmodSync, readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { homedir, platform, tmpdir } from 'node:os'
import { execSync } from 'node:child_process'

const PLIST_NAME = 'com.tokend.sync'
const PLIST_PATH = join(homedir(), 'Library', 'LaunchAgents', `${PLIST_NAME}.plist`)
const CRON_MARKER = '# tokend-auto-sync'
const TOKEND_DIR = join(homedir(), '.tokend')
const LOG_PATH = join(TOKEND_DIR, 'sync.log')
const WRAPPER_PATH = join(TOKEND_DIR, 'run-sync.sh')
const UPDATE_STAMP = join(TOKEND_DIR, '.last-update')
export const DAEMON_RUN_ENV = 'TOKEND_DAEMON_RUN'

// daemon 配置结构版本。每次改动 wrapper/plist 结构就 +1。
// daemon 自己跑时若检测到已装版本 < 此值，会自动重装升级（见 shouldAutoInstallDaemon）。
// v1: npx @latest 每次拉包（慢，96s）
// v2: 全局安装 + 跑全局 bin（秒级）+ 每日自更新 + 自升级闭环
export const DAEMON_VERSION = 2

function logDaemon(msg: string) {
  if (!existsSync(TOKEND_DIR)) mkdirSync(TOKEND_DIR, { recursive: true })
  appendFileSync(LOG_PATH, `[${new Date().toISOString()}] ${msg}\n`)
}

/**
 * Write a wrapper shell script to ~/.tokend/run-sync.sh
 *
 * Why a wrapper instead of pointing daemon directly to the binary?
 * - npx cache paths are volatile (change on version update, cache cleanup)
 * - Global install requires network + permissions, may fail
 * - A wrapper at a STABLE path (~/.tokend/) uses npx at runtime,
 *   which always resolves to the latest cached/installed version
 * - If one run fails (network, cache miss), next run retries — no permanent breakage
 */
export function buildWrapperScript(nodeBinDir: string, syncCmd: string, selfUpdate: boolean): string {
  // 全局 bin 模式：每天 npm i -g 更新一次（保持最新 + 触发 daemon 自升级），
  // 避免每次拉包；npx 模式自带 @latest，无需此块。
  const updateBlock = selfUpdate ? `
# 每日自更新全局包（保持最新，使 daemon 能检测到新版并自升级）
__now=$(date +%s)
__last=$(cat "${UPDATE_STAMP}" 2>/dev/null || echo 0)
if [ $((__now - __last)) -gt 86400 ]; then
  npm install -g tokend-cli@latest >/dev/null 2>&1 && echo "$__now" > "${UPDATE_STAMP}"
fi
` : ''
  return `#!/bin/bash
# Auto-generated by tokend-cli — do not edit
# tokend-daemon-version: ${DAEMON_VERSION}
# This script is run by the system daemon every 5 minutes
export HOME="${homedir()}"
export PATH="${nodeBinDir}:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin"
export npm_config_cache="${join(homedir(), '.npm')}"
export ${DAEMON_RUN_ENV}="1"
${updateBlock}
${syncCmd} 2>&1

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] sync failed (exit $EXIT_CODE)" >> "${LOG_PATH}"
fi
  `
}

/** 读取已安装 wrapper 的 daemon 版本标记；无 wrapper 或无标记视为 0（远古/未升级）。 */
export function installedDaemonVersion(): number {
  try {
    if (!existsSync(WRAPPER_PATH)) return 0
    const m = readFileSync(WRAPPER_PATH, 'utf8').match(/# tokend-daemon-version:\s*(\d+)/)
    return m ? parseInt(m[1], 10) : 0
  } catch {
    return 0
  }
}

/** npm 全局 bin 目录（`npm prefix -g`/bin）。用于在 nvm/自定义 prefix 下也能定位全局 bin。 */
function npmGlobalBinDir(): string {
  try {
    const prefix = execSync('npm prefix -g 2>/dev/null', { encoding: 'utf8' }).trim()
    if (prefix) return join(prefix, 'bin')
  } catch { /* ignore */ }
  return ''
}

/**
 * 定位已安装的全局 tokend-cli bin 绝对路径。
 * 关键：很多开发者用 nvm/自定义 npm prefix（如 ~/.npm-global），全局 bin 不在标准 PATH 里，
 * 所以 which 要带上 npm 全局 bin 目录，并以「直接拼路径」兜底——否则这批用户永远降级到 npx。
 */
function locateGlobalBin(): string {
  const globalBinDir = npmGlobalBinDir()
  try {
    const env = { ...process.env, PATH: `${globalBinDir}:${process.env.PATH || ''}` }
    const bin = execSync('which tokend-cli 2>/dev/null', { encoding: 'utf8', env }).trim()
    if (bin && existsSync(bin) && isStableDaemonBinaryPath(bin)) return bin
  } catch { /* not in PATH */ }
  if (globalBinDir) {
    const direct = join(globalBinDir, 'tokend-cli')
    if (existsSync(direct) && isStableDaemonBinaryPath(direct)) return direct
  }
  return ''
}

/**
 * install 时全局安装 tokend-cli@latest，返回稳定的全局 bin 绝对路径（供 wrapper 直接调用），
 * 失败返回 ''（fallback 到 npx，慢但永远可用）。最多尝试 2 次，覆盖首次拉包的偶发失败。
 */
function ensureGlobalInstall(): string {
  for (let i = 0; i < 2; i++) {
    try {
      execSync('npm install -g tokend-cli@latest', { stdio: 'ignore', timeout: 180000 })
    } catch {
      // 权限/网络失败 — 不致命，重试或 fallback 到 npx
    }
    const bin = locateGlobalBin()
    if (bin) return bin
  }
  return ''
}

function isStableDaemonBinaryPath(binPath: string): boolean {
  if (!binPath) return false
  if (binPath.includes('/.npm/_npx/')) return false
  if (binPath.includes('/node_modules/.bin/')) return false
  return true
}

export function resolveDaemonSyncCommand(globalBin: string): string {
  return isStableDaemonBinaryPath(globalBin)
    ? `"${globalBin}" --quiet`
    : 'npx --yes tokend-cli@latest --quiet'
}

function writeWrapper(): string {
  if (!existsSync(TOKEND_DIR)) mkdirSync(TOKEND_DIR, { recursive: true })

  // Resolve node/npx paths for the wrapper
  let nodeBinDir: string
  try {
    nodeBinDir = dirname(execSync('which node', { encoding: 'utf8' }).trim())
  } catch {
    nodeBinDir = dirname(process.execPath)
  }

  // 优先全局安装（秒级启动），失败则 fallback 到 npx（慢但永远可用、自带 @latest）
  const globalBin = ensureGlobalInstall()
  const syncCmd = resolveDaemonSyncCommand(globalBin)
  const selfUpdate = isStableDaemonBinaryPath(globalBin)  // 仅全局模式需要每日自更新

  const script = buildWrapperScript(nodeBinDir, syncCmd, selfUpdate)

  writeFileSync(WRAPPER_PATH, script)
  chmodSync(WRAPPER_PATH, 0o755)
  // 重置自更新时间戳：刚装/刚升级，避免下次 daemon 跑时立刻又触发一次 npm i -g
  try { writeFileSync(UPDATE_STAMP, String(Math.floor(Date.now() / 1000))) } catch { /* ignore */ }
  logDaemon(`Wrapper written v${DAEMON_VERSION}: ${WRAPPER_PATH} (cmd: ${syncCmd}, selfUpdate: ${selfUpdate})`)
  return WRAPPER_PATH
}

/**
 * 是否应自动（重）装 daemon。
 * - 用户手动运行（非 daemon 触发）：总是重装，刷新 node/script 路径。
 * - daemon 自己触发：仅当已装版本 < 当前 DAEMON_VERSION 才重装——这是「旧 daemon 自动
 *   升级到新 daemon」的闭环：旧 daemon 跑 npx @latest 拉到新 CLI，新 CLI 检测到版本旧，
 *   把自己升级成新 daemon（全局安装 + 秒级 wrapper）。版本相等则跳过，不浪费。
 */
export function shouldAutoInstallDaemon(env: NodeJS.ProcessEnv = process.env): boolean {
  if (env[DAEMON_RUN_ENV] !== '1') return true
  return installedDaemonVersion() < DAEMON_VERSION
}

// ─── macOS LaunchAgent ───

function buildPlist(wrapperPath: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_NAME}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${wrapperPath}</string>
  </array>
  <key>StartInterval</key>
  <integer>300</integer>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${LOG_PATH}</string>
  <key>StandardErrorPath</key>
  <string>${LOG_PATH}</string>
</dict>
</plist>
`
}

function installMacDaemon(silent: boolean) {
  const wrapperPath = writeWrapper()

  const laDir = dirname(PLIST_PATH)
  if (!existsSync(laDir)) mkdirSync(laDir, { recursive: true })

  writeFileSync(PLIST_PATH, buildPlist(wrapperPath))

  // ⚠️ 关键：当从 daemon 自身上下文触发重装（自升级）时，当前进程就是 launchd
  // 托管的 job 本身。launchctl unload 会向本进程组发 SIGTERM 自杀，后面的 load
  // 不会执行 → daemon 被永久卸载、全员哑火。而 plist 指向的 wrapper 路径是常量、
  // wrapper 内容已刷新，launchd 下次按 StartInterval 跑时自动读到新 wrapper，
  // 无需也绝不能 reload。仅用户手动安装（非 daemon 上下文）才做 unload/load。
  const fromDaemon = process.env[DAEMON_RUN_ENV] === '1'
  if (fromDaemon) {
    logDaemon(`macOS daemon upgraded in-place to v${DAEMON_VERSION} (wrapper refreshed, no reload)`)
  } else {
    try {
      execSync(`launchctl unload ${PLIST_PATH} 2>/dev/null`, { stdio: 'ignore' })
    } catch { /* ignore */ }
    execSync(`launchctl load ${PLIST_PATH}`)
    logDaemon(`macOS daemon installed v${DAEMON_VERSION}`)
  }

  if (!silent) {
    console.log('  ✓ 自动同步已开启 (每 5 分钟)')
    console.log(`    脚本: ${wrapperPath}`)
  }
  return true
}

// ─── Linux crontab ───

/**
 * 通过临时文件写 crontab，而非 `echo ... | crontab -`。
 * 旧写法用 JSON.stringify 转义换行成字面 \n，echo 不解释 → 整个 crontab 被压成一行，
 * 破坏用户其它 cron 任务。临时文件方式保留真实换行。
 */
function applyCrontab(content: string) {
  const tmp = join(tmpdir(), `tokend-crontab-${process.pid}-${Date.now()}.txt`)
  writeFileSync(tmp, content)
  try {
    execSync(`crontab "${tmp}"`)
  } finally {
    try { unlinkSync(tmp) } catch { /* ignore */ }
  }
}

function installLinuxDaemon(silent: boolean) {
  const wrapperPath = writeWrapper()

  const cronLine = `*/5 * * * * ${wrapperPath} >> ${LOG_PATH} 2>&1 ${CRON_MARKER}`

  let existing = ''
  try {
    existing = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' })
  } catch { /* no crontab yet */ }

  const filtered = existing.split('\n').filter(l => !l.includes(CRON_MARKER)).join('\n').trimEnd()
  const newCrontab = filtered ? `${filtered}\n${cronLine}\n` : `${cronLine}\n`

  applyCrontab(newCrontab)

  logDaemon(`Linux cron installed v${DAEMON_VERSION}`)
  if (!silent) {
    console.log('  ✓ 自动同步已开启 (每 5 分钟, crontab)')
    console.log(`    脚本: ${wrapperPath}`)
  }
  return true
}

// ─── Public API ───

export function installDaemon(silent = false): boolean {
  const os = platform()
  try {
    if (os === 'darwin') {
      return installMacDaemon(silent)
    } else if (os === 'linux') {
      return installLinuxDaemon(silent)
    } else {
      if (!silent) console.log(`  ⚠ 暂不支持 ${os} 自动同步，请手动定期运行: npx tokend-cli`)
      return false
    }
  } catch (err: any) {
    logDaemon(`ERROR installing daemon: ${err.message}`)
    if (!silent) console.error(`  ✗ 安装自动同步失败: ${err.message}`)
    return false
  }
}

export function uninstallDaemon() {
  const os = platform()

  if (os === 'darwin') {
    if (!existsSync(PLIST_PATH)) {
      console.log('  Daemon not installed')
      return
    }
    try {
      execSync(`launchctl unload ${PLIST_PATH}`)
    } catch { /* ignore */ }
    unlinkSync(PLIST_PATH)
    if (existsSync(WRAPPER_PATH)) unlinkSync(WRAPPER_PATH)
    console.log('  ✓ macOS daemon removed')
  } else if (os === 'linux') {
    try {
      const existing = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' })
      const filtered = existing.split('\n').filter(l => !l.includes(CRON_MARKER)).join('\n').trimEnd()
      applyCrontab(filtered ? filtered + '\n' : '')
      if (existsSync(WRAPPER_PATH)) unlinkSync(WRAPPER_PATH)
      console.log('  ✓ Cron job removed')
    } catch {
      console.log('  No cron job found')
    }
  } else {
    console.log(`  ⚠ ${os}: no daemon to remove`)
  }
}

export function daemonStatus() {
  const os = platform()

  if (os === 'darwin') {
    if (!existsSync(PLIST_PATH)) {
      console.log('  Daemon: not installed')
      console.log('  Run: npx tokend-cli daemon install')
      return
    }
    try {
      const out = execSync(`launchctl list ${PLIST_NAME} 2>&1`, { encoding: 'utf8' })
      const exitLine = out.split('\n').find(l => l.includes('LastExitStatus'))
      const pidLine = out.split('\n').find(l => l.includes('PID'))
      const exitCode = exitLine?.match(/(\d+)/)?.[1]
      const isOk = exitCode === '0' || exitCode === undefined

      if (pidLine) {
        console.log('  Daemon: running ✓')
        console.log(`  ${pidLine.trim()}`)
      } else if (isOk) {
        console.log('  Daemon: idle (waiting for next 5-min interval)')
      } else {
        console.log(`  Daemon: FAILING (exit ${exitCode})`)
        console.log('  Fix: npx tokend-cli daemon install')
      }
    } catch {
      console.log('  Daemon: installed but not running')
      console.log('  Fix: npx tokend-cli daemon install')
    }
  } else if (os === 'linux') {
    try {
      const crontab = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' })
      if (crontab.includes(CRON_MARKER)) {
        console.log('  Daemon: active (cron, every 5 min) ✓')
      } else {
        console.log('  Daemon: not installed')
        console.log('  Run: npx tokend-cli daemon install')
      }
    } catch {
      console.log('  Daemon: not installed')
      console.log('  Run: npx tokend-cli daemon install')
    }
  } else {
    console.log(`  ⚠ ${os}: auto-sync not supported`)
  }

  // Show wrapper info
  if (existsSync(WRAPPER_PATH)) {
    console.log(`  脚本: ${WRAPPER_PATH}`)
  }

  // Show recent log
  if (existsSync(LOG_PATH)) {
    try {
      const log = execSync(`tail -5 ${LOG_PATH}`, { encoding: 'utf8' }).trim()
      if (log) {
        console.log('\n  Recent log:')
        log.split('\n').forEach(l => console.log(`    ${l}`))
      }
    } catch { /* ignore */ }
  }
}
